server:
  port: 8080
  servlet:
    session:
      timeout: 86400
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video_recognize?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: rainboat
    password: rainboat
  mvc:
    static-path-pattern: /res/**
  web:
    resources:
      static-locations: file:${upload.image}, file:${upload.video}, file:${upload.files}
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 510MB
mybatis:
  type-aliases-package: com.neu.vedio_recognize.entity.po
  mapper-locations: classpath:sqlmap/*.xml
  config-location: classpath:mybatis-config.xml
logging:
  level:
    root: info
upload:
  video: /home/rainboat/video_recognize_res/videos
  image: /home/rainboat/video_recognize_res/images
  files: /home/rainboat/video_recognize_res/files
python-path: /home/rainboat/anaconda3/bin/python
script-path: /home/rainboat/video_recognize.py






